apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-helloworld
  name: python-helloworld
  namespace: sandbox
spec:
  ports:
  - port: 3111
    protocol: TCP
    targetPort: 3111
    nodePort: 30009
  selector:
    app: python-helloworld
  type: NodePort